runtime: go
api_version: go1.9

nobuild_files: (admin|api|rss|store)

handlers:
- url: /admin/static
  static_dir: admin/static
- url: /admin
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
