runtime: go111

nobuild_files: (admin|api|rss|store)

handlers:
- url: /admin/static.*
  static_dir: admin/static
- url: /admin.*
  script: _go_app
  login: admin
- url: /api.*
  script: _go_app
- url: /(.*\.(css|js|ico|png|jpg))$
  static_files: dist/\1
  upload: dist/.*
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  http_headers:
    Content-Type: text/html; charset=utf8
