runtime: go112

nobuild_files: (admin|api|rss|store)

env_variables:
  DATASTORE_PROJECT_ID: podcreep

# All requests route to our script, we handle static files manually.
handlers:
- url: /.*
  script: auto

