runtime: go111

nobuild_files: (admin|api|rss|store)

env_variables:
  DATASTORE_EMULATOR_HOST: localhost:23002
  DATASTORE_PROJECT_ID: podcreep

handlers:
- url: /admin/static.*
  static_dir: admin/static
- url: /admin.*
  script: auto
  login: admin
- url: /api.*
  script: auto
- url: /(.*\.(css|js|ico|png|jpg))$
  static_files: dist/\1
  upload: dist/.*
- url: /($|podcasts.*|discover.*) # TODO: this "/.*" pattern seems to be broken?
  static_files: dist/index.html
  upload: dist/index.html
  http_headers:
    Content-Type: text/html; charset=utf8
